### ISSUE TITLE
Privacy label crawler Not Working

### ISSUE THREAD

**Issue by annapaolagiancaspro** [xiaoyue10131748/Lalaine#2]
Hi

I was trying to retrieve the privacy labels of Google Maps and Snapchat apps. 
This is the file app_info.json

<img width="533" alt="Screenshot 2023-04-13 at 15 17 55" src="https://user-images.githubusercontent.com/83175380/231771258-0549c2de-e5ff-4fab-af50-c82878d8a08c.png">

and this is what happens:

<img width="2085" alt="Screenshot 2023-04-13 at 15 20 57" src="https://user-images.githubusercontent.com/83175380/231771620-8eebd231-f455-4453-836f-d6d08116d2b4.png">

Can you help me?

Thanks

**Comment by xiaoyue10131748** [comment]
You need to clean the original cached result in /label folder and run it again.

**Comment by annapaolagiancaspro** [comment]
Done, it's still the same

<img width="2278" alt="Screenshot 2023-04-13 at 15 53 30" src="https://user-images.githubusercontent.com/83175380/231780661-a1d4c6f7-285c-419c-977b-784c38a6127e.png">

**Comment by xiaoyue10131748** [comment]
The market is required to access the app. You can not remove it. Can you manually try "https://apps.apple.com/us/app/E-cards%20&%20Greetings/id958554522" to see if you can access this page?

**Comment by andyzyl** [comment]
@annapaolagiancaspro Hello. Here are two suggestions:
1) comment out line 107 _options.add_argument("--headless")_, so you can check whether your browser is opening or not.
2) check your google chrome's version and see if it compatible with the chromedriver:
https://sites.google.com/chromium.org/driver/
Please download the driver that matches your chrome version, otherwise the driver won't work.

Please let me know if you still have any questions. Thanks!

**Comment by annapaolagiancaspro** [comment]
It worked by inserting the country item on the json file for both the applications.
Without that even the browser was not opening. 
Thanks @xiaoyue10131748 and @andyzyl for your help!
